# Generated by Django 5.1.3 on 2024-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_propietario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
    ]
